print("What is your name?")
name=input()
print("How old are you?")
age=input()
print("How tall are you?")
height=input()
print("What is your weight?")
weight=input()
print("What is your favourite color?")
color=input()
